{
  "openapi": "3.0.1",
  "info": {
    "title": "Cradl AI API",
    "version": "2025-08-01T14:06:00Z"
  },
  "servers": [
    {
      "url": "https://api.lucidtech.ai/{basePath}",
      "variables": {
        "basePath": {
          "default": "v1"
        }
      }
    }
  ],
  "paths": {
    "/agents": {
      "get": {
        "x-mint": {
          "metadata": {
            "title": "List agents",
            "description": "List all agents.",
            "og:title": "List agents"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-mint": {
          "metadata": {
            "title": "Options for agents",
            "description": "Retrieve options for the agents endpoint.",
            "og:title": "Options for agents"
          }
        },
        "x-hidden": true
      },
      "post": {
        "x-mint": {
          "metadata": {
            "title": "Create agent",
            "description": "Create a new agent.",
            "og:title": "Create agent"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/agents/{agentId}": {
      "delete": {
        "x-mint": {
          "metadata": {
            "title": "Delete agent",
            "description": "Delete a specific agent.",
            "og:title": "Delete agent"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "get": {
        "x-mint": {
          "metadata": {
            "title": "Get agent",
            "description": "Get a specific agent.",
            "og:title": "Get agent"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-mint": {
          "metadata": {
            "title": "Options for agent",
            "description": "Retrieve options for a specific agent.",
            "og:title": "Options for agent"
          }
        },
        "x-hidden": true
      },
      "patch": {
        "x-mint": {
          "metadata": {
            "title": "Update agent",
            "description": "Update details of a specific agent.",
            "og:title": "Update agent"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/agents/{agentId}/runs": {
      "get": {
        "x-mint": {
          "metadata": {
            "title": "List agent runs",
            "description": "List all runs for a specific agent.",
            "og:title": "List agent runs"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "x-mint": {
          "metadata": {
            "title": "Create agent run",
            "description": "Create a new run for a specific agent.",
            "og:title": "Create agent run"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/agents/{agentId}/runs/{runId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "get": {
        "x-mint": {
          "metadata": {
            "title": "Get agent run",
            "description": "Get details of a specific run for an agent.",
            "og:title": "Get agent run"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          }
        ]
      }
    },
    "/documents": {
      "delete": {
        "x-mint": {
          "metadata": {
            "title": "Delete documents",
            "description": "Delete multiple documents.",
            "og:title": "Delete documents"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      },
      "get": {
        "x-mint": {
          "metadata": {
            "title": "List documents",
            "description": "Retrieve a list of documents.",
            "og:title": "List documents"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-mint": {
          "metadata": {
            "title": "Options for documents",
            "description": "Retrieve options for the documents endpoint.",
            "og:title": "Options for documents"
          }
        },
        "x-hidden": true
      },
      "post": {
        "x-mint": {
          "metadata": {
            "title": "Create document",
            "description": "Create a new document.",
            "og:title": "Create document"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/documents/{documentId}": {
      "delete": {
        "x-mint": {
          "metadata": {
            "title": "Delete document",
            "description": "Delete a specific document.",
            "og:title": "Delete document"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "get": {
        "x-mint": {
          "metadata": {
            "title": "Get document",
            "description": "Retrieve details of a specific document.",
            "og:title": "Get document"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-mint": {
          "metadata": {
            "title": "Options for document",
            "description": "Retrieve options for a specific document.",
            "og:title": "Options for document"
          }
        },
        "x-hidden": true
      },
      "patch": {
        "x-mint": {
          "metadata": {
            "title": "Update document",
            "description": "Update details of a specific document.",
            "og:title": "Update document"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/models": {
      "get": {
        "x-mint": {
          "metadata": {
            "title": "List models",
            "description": "Retrieve a list of models.",
            "og:title": "List models"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "x-mint": {
          "metadata": {
            "title": "Create model",
            "description": "Create a new model.",
            "og:title": "Create model"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          }
        ]
      }
    },
    "/models/{modelId}": {
      "delete": {
        "x-mint": {
          "metadata": {
            "title": "Delete model",
            "description": "Delete a specific model.",
            "og:title": "Delete model"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "get": {
        "x-mint": {
          "metadata": {
            "title": "Get model",
            "description": "Retrieve details of a specific model.",
            "og:title": "Get model"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "x-mint": {
          "metadata": {
            "title": "Update model",
            "description": "Update details of a specific model.",
            "og:title": "Update model"
          }
        },
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://auth.lucidtech.ai/oauth2/token",
            "scopes": {
              "api.lucidtech.ai/actions.runs:read": "Read permissions",
              "api.lucidtech.ai/actions.runs:write": "Write permissions",
              "api.lucidtech.ai/actions:read": "Read permissions",
              "api.lucidtech.ai/actions:write": "Write permissions",
              "api.lucidtech.ai/agents.runs:read": "Read permissions",
              "api.lucidtech.ai/agents.runs:write": "Write permissions",
              "api.lucidtech.ai/agents:read": "Read permissions",
              "api.lucidtech.ai/agents:write": "Write permissions",
              "api.lucidtech.ai/appclients:read": "Read permissions",
              "api.lucidtech.ai/appclients:write": "Write permissions",
              "api.lucidtech.ai/assets:read": "Read permissions",
              "api.lucidtech.ai/assets:write": "Write permissions",
              "api.lucidtech.ai/connections:read": "Read permissions",
              "api.lucidtech.ai/connections:write": "Write permissions",
              "api.lucidtech.ai/databundles:read": "Read permissions",
              "api.lucidtech.ai/databundles:write": "Write permissions",
              "api.lucidtech.ai/datasets:read": "Read permissions",
              "api.lucidtech.ai/datasets:write": "Write permissions",
              "api.lucidtech.ai/deploymentenvironments:read": "Read permissions",
              "api.lucidtech.ai/documents:read": "Read permissions",
              "api.lucidtech.ai/documents:write": "Write permissions",
              "api.lucidtech.ai/functions:read": "Read permissions",
              "api.lucidtech.ai/functions:write": "Write permissions",
              "api.lucidtech.ai/hooks.runs:read": "Read permissions",
              "api.lucidtech.ai/hooks.runs:write": "Write permissions",
              "api.lucidtech.ai/hooks:read": "Read permissions",
              "api.lucidtech.ai/hooks:write": "Write permissions",
              "api.lucidtech.ai/logs:read": "Read permissions",
              "api.lucidtech.ai/models:read": "Read permissions",
              "api.lucidtech.ai/models:write": "Write permissions",
              "api.lucidtech.ai/organizations:read": "Read permissions",
              "api.lucidtech.ai/organizations:write": "Write permissions",
              "api.lucidtech.ai/paymentmethods:read": "Read permissions",
              "api.lucidtech.ai/paymentmethods:write": "Write permissions",
              "api.lucidtech.ai/plans:read": "Read permissions",
              "api.lucidtech.ai/predictions:read": "Read permissions",
              "api.lucidtech.ai/predictions:write": "Write permissions",
              "api.lucidtech.ai/profiles:read": "Read permissions",
              "api.lucidtech.ai/profiles:write": "Write permissions",
              "api.lucidtech.ai/roles:read": "Read permissions",
              "api.lucidtech.ai/secrets:read": "Read permissions",
              "api.lucidtech.ai/secrets:write": "Write permissions",
              "api.lucidtech.ai/trainings:read": "Read permissions",
              "api.lucidtech.ai/trainings:write": "Write permissions",
              "api.lucidtech.ai/transformations:read": "Read permissions",
              "api.lucidtech.ai/transformations:write": "Write permissions"
            }
          }
        }
      }
    }
  }
}
