{
  "openapi": "3.0.1",
  "info": {
    "title": "Cradl AI API",
    "version": "2025-08-01T14:06:00Z"
  },
  "servers": [
    {
      "url": "https://api.lucidtech.ai/{basePath}",
      "variables": {
        "basePath": {
          "default": "v1"
        }
      }
    }
  ],
  "paths": {
    "/actions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/actions/{actionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/actions/{actionId}/runs": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/actions/{actionId}/runs/{runId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/agents": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/agents/{agentId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/agents/{agentId}/runs": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/agents/{agentId}/runs/{runId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          }
        ]
      }
    },
    "/appClients": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/appClients/{appClientId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/assets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/assets/{assetId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/connections": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/connections/{connectionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/datasets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/datasets/{datasetId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/datasets:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/datasets/{datasetId}/transformations": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/datasets/{datasetId}/transformations/{transformationId}": {
      "delete": {
        "security": [],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/deploymentEnvironments": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/deploymentEnvironments/{deploymentEnvironmentId}": {
      "get": {
        "security": [],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/documents": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/documents/{documentId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ]
      }
    },
    "/functions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/functions/{functionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/appclients:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/hooks": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/hooks/{hookId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/hooks/{hookId}/runs": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/hooks/{hookId}/runs/{runId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/logs": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/logs:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/logs/{logId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/logs:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/models": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          }
        ]
      }
    },
    "/models/{modelId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ]
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          }
        ]
      }
    },
    "/models/{modelId}/dataBundles": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/models/{modelId}/dataBundles/{dataBundleId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/models/{modelId}/trainings": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/models/{modelId}/trainings/{trainingId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/databundles:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/organizations": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/organizations/{organizationId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/organizations:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/paymentMethods": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/paymentMethods/{paymentMethodId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/plans": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/plans:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/plans/{planId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/plans:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/predictions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/predictions/{predictionId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/predictions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/profiles/{profileId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/assets:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/roles": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/roles/{roleId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      }
    },
    "/secrets": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/secrets/{secretId}": {
      "delete": {
        "security": [],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/transitions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/transitions/{transitionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/transitions/{transitionId}/executions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/transitions/{transitionId}/executions/{executionId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/transitions/{transitionId}/executions/{executionId}/heartbeats": {
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/transitions.executions.heartbeats:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/users": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/users/{userId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/users:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/validations": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/paymentmethods:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/validations/{validationId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/models:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/validations/{validationId}/tasks": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/documents:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/validations/{validationId}/tasks/{taskId}": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/secrets:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/workflows": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/workflows/{workflowId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/workflows/{workflowId}/executions": {
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "post": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:write"
            ]
          }
        ],
        "x-hidden": true
      }
    },
    "/workflows/{workflowId}/executions/{executionId}": {
      "delete": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "get": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:read"
            ]
          }
        ],
        "x-hidden": true
      },
      "options": {
        "x-hidden": true
      },
      "patch": {
        "security": [
          {
            "OAuth2": [
              "api.lucidtech.ai/workflows.executions:write"
            ]
          }
        ],
        "x-hidden": true
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://auth.lucidtech.ai/oauth2/token",
            "scopes": {
              "api.lucidtech.ai/actions.runs:read": "Read permissions",
              "api.lucidtech.ai/actions.runs:write": "Write permissions",
              "api.lucidtech.ai/actions:read": "Read permissions",
              "api.lucidtech.ai/actions:write": "Write permissions",
              "api.lucidtech.ai/agents.runs:read": "Read permissions",
              "api.lucidtech.ai/agents.runs:write": "Write permissions",
              "api.lucidtech.ai/agents:read": "Read permissions",
              "api.lucidtech.ai/agents:write": "Write permissions",
              "api.lucidtech.ai/appclients:read": "Read permissions",
              "api.lucidtech.ai/appclients:write": "Write permissions",
              "api.lucidtech.ai/assets:read": "Read permissions",
              "api.lucidtech.ai/assets:write": "Write permissions",
              "api.lucidtech.ai/connections:read": "Read permissions",
              "api.lucidtech.ai/connections:write": "Write permissions",
              "api.lucidtech.ai/databundles:read": "Read permissions",
              "api.lucidtech.ai/databundles:write": "Write permissions",
              "api.lucidtech.ai/datasets:read": "Read permissions",
              "api.lucidtech.ai/datasets:write": "Write permissions",
              "api.lucidtech.ai/deploymentenvironments:read": "Read permissions",
              "api.lucidtech.ai/documents:read": "Read permissions",
              "api.lucidtech.ai/documents:write": "Write permissions",
              "api.lucidtech.ai/functions:read": "Read permissions",
              "api.lucidtech.ai/functions:write": "Write permissions",
              "api.lucidtech.ai/hooks.runs:read": "Read permissions",
              "api.lucidtech.ai/hooks.runs:write": "Write permissions",
              "api.lucidtech.ai/hooks:read": "Read permissions",
              "api.lucidtech.ai/hooks:write": "Write permissions",
              "api.lucidtech.ai/logs:read": "Read permissions",
              "api.lucidtech.ai/models:read": "Read permissions",
              "api.lucidtech.ai/models:write": "Write permissions",
              "api.lucidtech.ai/organizations:read": "Read permissions",
              "api.lucidtech.ai/organizations:write": "Write permissions",
              "api.lucidtech.ai/paymentmethods:read": "Read permissions",
              "api.lucidtech.ai/paymentmethods:write": "Write permissions",
              "api.lucidtech.ai/plans:read": "Read permissions",
              "api.lucidtech.ai/predictions:read": "Read permissions",
              "api.lucidtech.ai/predictions:write": "Write permissions",
              "api.lucidtech.ai/profiles:read": "Read permissions",
              "api.lucidtech.ai/profiles:write": "Write permissions",
              "api.lucidtech.ai/roles:read": "Read permissions",
              "api.lucidtech.ai/secrets:read": "Read permissions",
              "api.lucidtech.ai/secrets:write": "Write permissions",
              "api.lucidtech.ai/trainings:read": "Read permissions",
              "api.lucidtech.ai/trainings:write": "Write permissions",
              "api.lucidtech.ai/transformations:read": "Read permissions",
              "api.lucidtech.ai/transformations:write": "Write permissions",
              "api.lucidtech.ai/transitions.executions.heartbeats:write": "Write permissions",
              "api.lucidtech.ai/transitions.executions:read": "Read permissions",
              "api.lucidtech.ai/transitions.executions:write": "Write permissions",
              "api.lucidtech.ai/transitions:read": "Read permissions",
              "api.lucidtech.ai/transitions:write": "Write permissions",
              "api.lucidtech.ai/users:read": "Read permissions",
              "api.lucidtech.ai/users:write": "Write permissions",
              "api.lucidtech.ai/validations.tasks:read": "Read permissions",
              "api.lucidtech.ai/validations.tasks:write": "Write permissions",
              "api.lucidtech.ai/validations:read": "Read permissions",
              "api.lucidtech.ai/validations:write": "Write permissions",
              "api.lucidtech.ai/workflows.executions:read": "Read permissions",
              "api.lucidtech.ai/workflows.executions:write": "Write permissions",
              "api.lucidtech.ai/workflows:read": "Read permissions",
              "api.lucidtech.ai/workflows:write": "Write permissions"
            }
          }
        }
      }
    }
  }
}
